### PR TITLE
feat: multi line notes

### PR DESCRIPTION
**Pull request by KillerCodeMonkey**
Added multi line notes for time entries

+ placeholder for time input (to know what to enter)
+ extended the formatting of the time entry in the day view - max 80 chars of the notes and make single line

PS: Nice project! (i had the idea to greate an own time tracking app for harvest, but why not working at one :))
PPS: This is the first time i am doing anything with rust and gtk - please be kind :D

Sadly gtk is a little bit strange to work with. (i tried to add the gtk::Entry css classes to the textview to get the round borders and background colors, but no luck, or just adding placeholders for the comboboxes and textview). Even the grid behaves/works a little bit strange, if you are coming from web dev.

### CODE REVIEW

**Comment by frenkel** [comment]
Works great, thank you! I have nothing to complain, this really makes it a better app :smile:
I'll try to build and release a new version this weekend.

**Comment by KillerCodeMonkey** [comment]
yeah! nice. thanks. maybe i will create a another pbi til the release like scrollview in the main window to have a fixed max height and scrollable content

**Comment by frenkel** [comment]
That would be great, it can get quite weird how GTK handles the window size :roll_eyes:

**Comment by KillerCodeMonkey** [comment]
Indeed!

In general i am just using web techs + electron to build cross platform apps, but since i have a brand new linux machine, i missed the mac harvest app. And i just take the opportunity to get more into rust and "real" OS app development. And with electron you get huge apps even if they do nothing.

**Comment by frenkel** [comment]
Would it be possible to disable the tab key in the textview and keep it to switch the focus of elements?

**Comment by KillerCodeMonkey** [comment]
i think this is possible. I found it. https://gtk-rs.org/docs/gtk/trait.TextViewExt.html#tymethod.set_accepts_tab

**Comment by KillerCodeMonkey** [comment]
done!

**Comment by frenkel** [comment]
:tada:

**Pull request merged**
